/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prodigy4440.view;

import javax.swing.text.Highlighter;

/**
 *
 * @author prodigy4440
 */
public class FindAndReplaceJDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
    private final MainJFrame mainJFrame;

    /**
     * Creates new form FindAndReplaceJDialog
     *
     * @param parent
     * @param modal
     */
    public FindAndReplaceJDialog(java.awt.Frame parent, boolean modal, MainJFrame mainJFrame) {
        super(parent, modal);
        initComponents();
        this.mainJFrame = mainJFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        findJTextField = new javax.swing.JTextField();
        replaceJTextField = new javax.swing.JTextField();
        matchWordJCheckBox = new javax.swing.JCheckBox();
        findJButton = new javax.swing.JButton();
        findAllJButton = new javax.swing.JButton();
        replaceJButton = new javax.swing.JButton();
        replaceAllJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Find and Replace");

        jLabel1.setText("Find : ");

        jLabel2.setText("Replace :");

        matchWordJCheckBox.setText("Match Word");
        matchWordJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchWordJCheckBoxActionPerformed(evt);
            }
        });

        findJButton.setText("Find");
        findJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findJButtonActionPerformed(evt);
            }
        });

        findAllJButton.setText("Find All");
        findAllJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findAllJButtonActionPerformed(evt);
            }
        });

        replaceJButton.setText("Replace");
        replaceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceJButtonActionPerformed(evt);
            }
        });

        replaceAllJButton.setText("Replace All");
        replaceAllJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceAllJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(replaceJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(replaceAllJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(matchWordJCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(findJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findAllJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(replaceJTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(findJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matchWordJCheckBox)
                    .addComponent(findJButton)
                    .addComponent(findAllJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceJButton)
                    .addComponent(replaceAllJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matchWordJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchWordJCheckBoxActionPerformed

    }//GEN-LAST:event_matchWordJCheckBoxActionPerformed

    private void findJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findJButtonActionPerformed
        if (!findJTextField.getText().isEmpty()) {
            if (matchWordJCheckBox.isSelected()) {
                mainJFrame.wordSearcher.search(findJTextField.getText().trim(), true, 1);
            } else {
                mainJFrame.wordSearcher.search(findJTextField.getText().trim(), false, 1);
            }
        }
    }//GEN-LAST:event_findJButtonActionPerformed

    private void findAllJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findAllJButtonActionPerformed
        if (!findJTextField.getText().isEmpty()) {
            if (matchWordJCheckBox.isSelected()) {
                mainJFrame.wordSearcher.search(findJTextField.getText().trim(), true, 4);
            } else {
                mainJFrame.wordSearcher.search(findJTextField.getText().trim(), false, 4);
            }
        }
    }//GEN-LAST:event_findAllJButtonActionPerformed

    private void replaceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceJButtonActionPerformed
        Highlighter highlighter = mainJFrame.textArea.getHighlighter();
        Highlighter.Highlight[] highlights = highlighter.getHighlights();
        String replace = new String();

        if (!replaceJTextField.getText().isEmpty()) {
            replace = replaceJTextField.getText().trim();
            for (Highlighter.Highlight highlight : highlights) {
                mainJFrame.textArea.replaceRange(replace, highlight.getStartOffset(), highlight.getEndOffset());
                break;
            }
        }

    }//GEN-LAST:event_replaceJButtonActionPerformed

    private void replaceAllJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceAllJButtonActionPerformed
        Highlighter highlighter = mainJFrame.textArea.getHighlighter();
        Highlighter.Highlight[] highlights = highlighter.getHighlights();
        String replace = new String();

        if (!replaceJTextField.getText().isEmpty()) {
            replace = replaceJTextField.getText().trim();
            for (Highlighter.Highlight highlight : highlights) {
                mainJFrame.textArea.replaceRange(replace, highlight.getStartOffset(), highlight.getEndOffset());

            }
        }
    }//GEN-LAST:event_replaceAllJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton findAllJButton;
    private javax.swing.JButton findJButton;
    private javax.swing.JTextField findJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox matchWordJCheckBox;
    private javax.swing.JButton replaceAllJButton;
    private javax.swing.JButton replaceJButton;
    private javax.swing.JTextField replaceJTextField;
    // End of variables declaration//GEN-END:variables

}
