/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prodigy4440.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.TabSet;
import javax.swing.text.TabStop;

/**
 *
 * @author prodigy4440
 */
public class HelpJDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1897946389L;

    /**
     * Creates new form HelpJDialog
     *
     * @param parent
     * @param modal
     */
    public HelpJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        StyledDocument document = new DefaultStyledDocument();

        TabStop tabstop = new TabStop(150, TabStop.ALIGN_CENTER, TabStop.LEAD_DOTS);
        SimpleAttributeSet attributes = new SimpleAttributeSet();
        attributes.addAttribute(StyleConstants.CharacterConstants.Bold,
                Boolean.TRUE);

        try {
            TabSet tabset = new TabSet(new TabStop[]{tabstop});
            StyleConstants.setTabSet(attributes, tabset);
            document.insertString(document.getLength(), "\t         Yoruba Text Editor\n",
                    attributes);

        } catch (BadLocationException badLocationException) {
            System.err.println("Bad insert");
        }

        attributes = new SimpleAttributeSet();
        attributes.addAttribute(StyleConstants.CharacterConstants.BidiLevel, Boolean.TRUE);
        attributes.addAttribute(SwingConstants.CENTER, Boolean.TRUE);

        try {
            document.insertString(document.getLength(), help, attributes);
        } catch (BadLocationException ex) {
            Logger.getLogger(HelpJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        helpJTextPane.setDocument(document);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        helpJTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");

        closeJButton.setText("Close");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        helpJTextPane.setEditable(false);
        jScrollPane1.setViewportView(helpJTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 279, Short.MAX_VALUE)
                        .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;
    private javax.swing.JTextPane helpJTextPane;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    String help = "\tYoruba text editor is text editing"
            + " application for entering yoruba character set and tone marking "
            + "them in way to have the proper feel have the reality of true "
            + "editing.\n"
            + "Character mapping\n"
            + "\tQ is for \u1e62\n"
            + "\tC is for \u1eb9\n"
            + "\tV is for \u1ecd\n"
            + "\tZ is for Grave i.e do\n"
            + "\tX is for Acute i.e mi\n"
            + "\tAlternative Grave is ctrl+' i.e ctrl + single quote"
            + "\tAlternative Acute is alt +' i.e alt + single quote\n"
            + ""
            + "Files are saved in utf8 encoding.\n"
            + "Enjoy!";

}
